# Default values for the quarkus-ci-cd chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# --- Application Configuration ---
# The name of the application. This will be used to name resources.
appName: "eqt-poc-quarkus"
# The OpenShift project (namespace) where the application will be deployed.
openshiftProject: "eqt-poc-quarkus-qas"
# --- Git Repository Configuration ---
git:
  repoURL: "https://github.com/rsoares21/eqt-poc-quarkus.git"
  targetRevision: "main"
# --- Container Image Configuration ---
image:
  # The name of the image to build. The part after the slash should match the pom.xml <artifactId>.
  name: "rsoares21/eqt-poc-quarkus"
  # The tag of the image to build.
  tag: "74279b2d4061a7227b536119b14a5fdf033e6bbd"
  # The URL of the container registry.
  # For OpenShift internal registry, use: "image-registry.openshift-image-registry.svc:5000"
  registryURL: "image-registry.openshift-image-registry.svc:5000"
# --- ArgoCD Configuration ---
argoCD:
  # The namespace where ArgoCD is running.
  namespace: "openshift-gitops"


